defaultPlacement: end
enableVersioning: true
entryTypes:
  - e3d39713-9ffa-4e92-8243-4ae17ce3987b # About
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ecf43ff5-d5de-44a0-9c21-81afbe1b726c: # cms test aug
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
