defaultPlacement: end
enableVersioning: true
entryTypes:
  - edc1bfe8-f825-4996-8b0d-efe392379f8e # Post
  - 834ec624-ea3a-445f-8e6e-bc5c217ff2ab # Default
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ecf43ff5-d5de-44a0-9c21-81afbe1b726c: # cms test aug
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
